;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sentence
        beginning-of-visual-line
        counsel-yank-pop
        crux-move-beginning-of-line
        cycle-spacing
        end-of-visual-line
        ibuffer-do-delete
        ibuffer-mark-forward
        indent-for-tab-command
        kill-visual-line
        org-beginning-of-line
        org-ctrl-c-ctrl-c
        org-delete-char
        org-end-of-line
        org-kill-line
        org-return
        org-self-insert-command
        org-yank
        paredit-backward-kill-word
        sp-backward-delete-char
        sp-backward-kill-word
        sp-backward-unwrap-sexp
        sp-delete-char
        sp-forward-slurp-sexp
        sp-kill-hybrid-sexp
        sp-kill-word
        sp-remove-active-pair-overlay
        sp-splice-sexp
        sp-unwrap-sexp
        toggle-comment-on-line
        wgrep-finish-edit
        whole-line-or-region-kill-region
        whole-line-or-region-kill-ring-save
        whole-line-or-region-yank
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        ace-window
        counsel-M-x
        dap-tooltip-mouse-motion
        hydra--digit-argument
        ignore
        mouse-set-region
        org-cycle
        org-edit-src-save
        wgrep-change-to-wgrep-mode
        yh/whole-line-or-region-kill-ring-save
        ))
